### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by JimBrouzoulis** [springload/Wrangler.py#1]
Wondering what kind of license applies to the project? Couldn't find any license file or any reference to it. 
Thanks in advance.

**Comment by loicteixeira** [comment]
We usually release all our packages under MIT.

It is actually mentioned in [setup.py](https://github.com/springload/Wrangler.py/blob/9607c00b832aecda0d591d93ae842f90a330708b/setup.py#L14) but I'll add a `LICENSE` file to the root of the directory. Thanks for the heads up.
